export type Term = {
  term: string;
  en: string;
  level: "beginner" | "advanced";
  def: string;
};

export const GLOSSARY_TERMS: Term[] = [
  { term: "大模型", en: "LLM", level: "beginner",
    def: "在海量文本上训练、擅长理解和生成自然语言的超大神经网络。核心能力是预测下一个词。" },
  { term: "Token（词元）", en: "Token", level: "beginner",
    def: "模型处理文字的最小单位，一个中文字约 1~2 个 token。模型按 token 读写，API 也按 token 计费。" },
  { term: "上下文窗口", en: "Context Window", level: "beginner",
    def: "模型一次能「记住」的 token 上限。超出部分会被遗忘，决定了它能处理多长的文档或对话。" },
  { term: "参数", en: "Parameters", level: "beginner",
    def: "模型内部可学习的数值，数量从数十亿到上万亿。通常参数越多，能力上限越高。" },
  { term: "提示词", en: "Prompt", level: "beginner",
    def: "你给模型的输入指令。提示写得越清楚（背景、角色、格式、例子），回答质量越高。" },
  { term: "幻觉", en: "Hallucination", level: "beginner",
    def: "模型一本正经地编造看似可信但错误的内容。它追求「读起来合理」而非「事实正确」。" },
  { term: "预训练", en: "Pre-training", level: "beginner",
    def: "模型的第一阶段学习：阅读海量文本，掌握语言规律和世界知识，打下能力基础。" },
  { term: "微调", en: "Fine-tuning", level: "advanced",
    def: "在预训练模型基础上，用特定领域数据继续训练，让它固化某种风格或专业能力。" },
  { term: "RLHF", en: "RLHF", level: "advanced",
    def: "基于人类反馈的强化学习。用人类的示范和打分「教」模型怎样回答更有用、更安全。" },
  { term: "思维链", en: "Chain-of-Thought", level: "advanced",
    def: "让模型「一步步思考」再给结论的提示技巧，能显著提升复杂推理的准确率。" },
  { term: "少样本提示", en: "Few-shot", level: "advanced",
    def: "在提示里给出一两个示例，锚定模型输出的风格与格式。不给例子叫 zero-shot。" },
  { term: "系统提示", en: "System Prompt", level: "advanced",
    def: "设定模型全局角色、规则与边界的隐藏指令，优先级高于普通对话内容。" },
  { term: "温度", en: "Temperature", level: "advanced",
    def: "控制输出随机性的参数。低（如 0.2）更稳定确定，高（如 0.9）更有创意发散。" },
  { term: "RAG", en: "Retrieval-Augmented Generation", level: "advanced",
    def: "检索增强生成：先从知识库检索相关资料，再让模型基于资料回答，大幅降低幻觉。" },
  { term: "向量化", en: "Embedding", level: "advanced",
    def: "把文字转成一串数字（向量），让语义相近的内容在数学空间里也相近，是检索和 RAG 的基础。" },
  { term: "向量数据库", en: "Vector Database", level: "advanced",
    def: "专门存储和检索向量的数据库，能按「语义相似度」快速找出最相关的内容。" },
  { term: "智能体", en: "Agent", level: "advanced",
    def: "大模型 + 工具 + 循环：能自主拆解任务、调用工具、根据结果决定下一步的 AI 系统。" },
  { term: "工具调用", en: "Function Calling", level: "advanced",
    def: "让模型按需调用外部函数/API（如搜索、计算、查数据库）的能力，是 Agent 的基础。" },
  { term: "MCP", en: "Model Context Protocol", level: "advanced",
    def: "一种把外部工具和数据源标准化接入大模型的开放协议，让 Agent 接工具更通用。" },
  { term: "多模态", en: "Multimodal", level: "beginner",
    def: "模型不只处理文字，还能理解或生成图片、音频、视频等多种形式的内容。" },
  { term: "推理模型", en: "Reasoning Model", level: "advanced",
    def: "会先「思考」一段再作答的模型，擅长数学、代码等复杂推理，但更慢更贵。" },
  { term: "Transformer", en: "Transformer", level: "advanced",
    def: "现代大模型的核心架构，靠「自注意力机制」理解上下文，支持大规模并行训练。" },
  { term: "注意力机制", en: "Attention", level: "advanced",
    def: "让模型在处理每个词时，权衡上下文里其他词的重要性，从而理解长距离语义关联。" },
  { term: "流式输出", en: "Streaming", level: "advanced",
    def: "模型边生成边逐字返回结果（像打字机效果），无需等全部生成完，体验更流畅。" },
  { term: "提示注入", en: "Prompt Injection", level: "advanced",
    def: "攻击者通过精心构造的输入「劫持」模型，绕过或篡改原本的系统指令，是重要安全风险。" },
  { term: "开源 / 闭源", en: "Open / Closed Weights", level: "beginner",
    def: "开源模型（如 Llama、Qwen、DeepSeek）权重公开、可私有部署；闭源（如 GPT、Claude）只能通过 API 使用。" },
  { term: "模型蒸馏", en: "Distillation", level: "advanced",
    def: "用大模型「教」小模型，把能力压缩进更小、更便宜、更快的模型里。" },
  { term: "量化", en: "Quantization", level: "advanced",
    def: "把模型参数用更低精度存储（如 16 位降到 4 位），大幅减小体积、降低显存占用，略损精度。" },
];
